# Generated by Django 5.0.6 on 2025-08-04 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='系統名稱')),
                ('system_type', models.CharField(choices=[('control', '對照組'), ('experiment', '實驗組')], max_length=20, verbose_name='系統類型')),
                ('location', models.CharField(max_length=100, verbose_name='場域位置')),
                ('description', models.TextField(blank=True, verbose_name='系統描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '系統組別',
                'verbose_name_plural': '系統組別',
            },
        ),
        migrations.CreateModel(
            name='PowerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記錄時間')),
                ('voltage', models.FloatField(help_text='太陽能板輸出電壓', verbose_name='電壓(V)')),
                ('current', models.FloatField(help_text='太陽能板輸出電流', verbose_name='電流(A)')),
                ('power_output', models.FloatField(help_text='計算或測量的功率', verbose_name='功率(W)')),
                ('light_intensity', models.FloatField(blank=True, null=True, verbose_name='光照強度(lux)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='溫度(°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='濕度(%)')),
                ('panel_azimuth', models.FloatField(blank=True, null=True, verbose_name='方位角(°)')),
                ('panel_tilt', models.FloatField(blank=True, null=True, verbose_name='傾角(°)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記錄建立時間')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.systemgroup', verbose_name='所屬系統')),
            ],
            options={
                'verbose_name': '發電記錄',
                'verbose_name_plural': '發電記錄',
                'ordering': ['-timestamp'],
            },
        ),
    ]
