# Generated by Django 5.0.6 on 2025-10-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_angle',
            field=models.FloatField(blank=True, help_text='線性致動器(推桿)當前角度', null=True, verbose_name='推桿角度(°)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_current',
            field=models.FloatField(blank=True, help_text='線性致動器(推桿)的工作電流', null=True, verbose_name='推桿電流(A)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_extension',
            field=models.FloatField(blank=True, help_text='線性致動器(推桿)當前伸展長度', null=True, verbose_name='推桿伸展長度(mm)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_power',
            field=models.FloatField(blank=True, help_text='線性致動器(推桿)的功耗', null=True, verbose_name='推桿功率(W)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_voltage',
            field=models.FloatField(blank=True, help_text='線性致動器(推桿)的工作電壓', null=True, verbose_name='推桿電壓(V)'),
        ),
    ]
