# Generated by Django 5.0.6 on 2026-01-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_powerrecord_actuator_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_total_current',
            field=models.FloatField(blank=True, help_text='兩根推桿的總電流', null=True, verbose_name='推桿總電流(A)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_total_power',
            field=models.FloatField(blank=True, help_text='兩根推桿的總功耗', null=True, verbose_name='推桿總功率(W)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='actuator_total_voltage',
            field=models.FloatField(blank=True, help_text='兩根推桿的總電壓', null=True, verbose_name='推桿總電壓(V)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='ew_actuator_angle',
            field=models.FloatField(blank=True, help_text='東西方向推桿當前角度', null=True, verbose_name='東西推桿角度(°)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='ew_actuator_extension',
            field=models.FloatField(blank=True, help_text='東西方向推桿當前伸展長度', null=True, verbose_name='東西推桿伸展長度(mm)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='ns_actuator_angle',
            field=models.FloatField(blank=True, help_text='南北方向推桿當前角度', null=True, verbose_name='南北推桿角度(°)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='ns_actuator_extension',
            field=models.FloatField(blank=True, help_text='南北方向推桿當前伸展長度', null=True, verbose_name='南北推桿伸展長度(mm)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='raspberry_pi_current',
            field=models.FloatField(blank=True, help_text='Raspberry Pi 的工作電流', null=True, verbose_name='樹莓派電流(A)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='raspberry_pi_power',
            field=models.FloatField(blank=True, help_text='Raspberry Pi 的功耗', null=True, verbose_name='樹莓派功率(W)'),
        ),
        migrations.AddField(
            model_name='powerrecord',
            name='raspberry_pi_voltage',
            field=models.FloatField(blank=True, help_text='Raspberry Pi 的工作電壓', null=True, verbose_name='樹莓派電壓(V)'),
        ),
        migrations.AlterField(
            model_name='powerrecord',
            name='actuator_angle',
            field=models.FloatField(blank=True, help_text='[已棄用] 建議使用 ns_actuator_angle 或 ew_actuator_angle', null=True, verbose_name='推桿角度(°)(舊)'),
        ),
        migrations.AlterField(
            model_name='powerrecord',
            name='actuator_current',
            field=models.FloatField(blank=True, help_text='[已棄用] 建議使用 actuator_total_current', null=True, verbose_name='推桿電流(A)(舊)'),
        ),
        migrations.AlterField(
            model_name='powerrecord',
            name='actuator_extension',
            field=models.FloatField(blank=True, help_text='[已棄用] 建議使用 ns_actuator_extension 或 ew_actuator_extension', null=True, verbose_name='推桿伸展長度(mm)(舊)'),
        ),
        migrations.AlterField(
            model_name='powerrecord',
            name='actuator_power',
            field=models.FloatField(blank=True, help_text='[已棄用] 建議使用 actuator_total_power', null=True, verbose_name='推桿功率(W)(舊)'),
        ),
        migrations.AlterField(
            model_name='powerrecord',
            name='actuator_voltage',
            field=models.FloatField(blank=True, help_text='[已棄用] 建議使用 actuator_total_voltage', null=True, verbose_name='推桿電壓(V)(舊)'),
        ),
        migrations.AddIndex(
            model_name='powerrecord',
            index=models.Index(fields=['-timestamp'], name='idx_timestamp'),
        ),
        migrations.AddIndex(
            model_name='powerrecord',
            index=models.Index(fields=['system'], name='idx_system'),
        ),
        migrations.AddIndex(
            model_name='powerrecord',
            index=models.Index(fields=['system', '-timestamp'], name='idx_system_timestamp'),
        ),
    ]
